Repository FrangipaneTeam/terraform-plugin-framework-validators, pull requests merged in 2023-03, with the labels that each got.

#20 feat: add `IsURN` list validator
  docs/listvalidator/index.md
  docs/listvalidator/isurn.md
  go.mod
  go.sum
  listvalidator/common/valid_with_regex.go
  listvalidator/is_urn.go
  listvalidator/is_urn_test.go
Labels: enhancement

#36 fix: Missing documentation for `IsMacAddress` string validator (#35)
  docs/stringvalidator/index.md
  docs/stringvalidator/ismacaddress.md
Labels: documentation

#40 feat: add new validator `require_if_attribute_is_one_of`
  boolvalidator/require_if_attribute_is_one_of.go
  docs/boolvalidator/index.md
  docs/common/require_if_attribute_is_one_of.md
  docs/int64validator/index.md
  docs/listvalidator/index.md
  docs/mapvalidator/index.md
  docs/setvalidator/index.md
  docs/stringvalidator/index.md
  go.mod
  go.sum
  int64validator/require_if_attribute_is_one_of.go
  internal/require_if_attribute_is_one_of.go
  internal/require_if_attribute_is_one_of_test.go
  listvalidator/require_if_attribute_is_one_of.go
  mapvalidator/require_if_attribute_is_one_of.go
  setvalidator/require_if_attribute_is_one_of.go
  stringvalidator/require_if_attribute_is_one_of.go
Labels: Feature, size/L

#42 fix: error message and docs for `RequireIfAttributeIsOneOf`
  docs/boolvalidator/not.md
  docs/common/require_if_attribute_is_one_of.md
  internal/require_if_attribute_is_one_of.go
Labels: size/XS, Fix
